name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout project
        uses: actions/checkout@v4

      - name: Show project files
        run: |
          echo "===== PROJECT FILES ====="
          find . -type f | sort

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Download and install Gradle
        run: |
          wget -q https://services.gradle.org/distributions/gradle-8.7-bin.zip
          unzip -q gradle-8.7-bin.zip
          echo "$PWD/gradle-8.7/bin" >> "$GITHUB_PATH"

      - name: Check app assets
        run: |
          echo "===== ASSETS ====="

          if [ -d "app/src/main/assets" ]; then
            find app/src/main/assets -type f -exec ls -lh {} \;
          else
            echo "WARNING: app/src/main/assets folder NOT FOUND"
          fi

      - name: Clean project
        run: |
          gradle clean

      - name: Build Debug APK
        run: |
          gradle :app:assembleDebug --stacktrace

      - name: Check generated APK
        run: |
          echo "===== APK FILE ====="

          APK="app/build/outputs/apk/debug/app-debug.apk"

          if [ ! -f "$APK" ]; then
            echo "ERROR: APK was not generated!"
            exit 1
          fi

          ls -lh "$APK"

          echo ""
          echo "===== FILE TYPE ====="
          file "$APK"

          echo ""
          echo "===== APK CONTENTS ====="
          unzip -t "$APK"

      - name: Verify APK signature
        run: |
          APK="app/build/outputs/apk/debug/app-debug.apk"

          BUILD_TOOLS=$(find "$ANDROID_HOME/build-tools" -maxdepth 1 -type d | sort -V | tail -n 1)

          "$BUILD_TOOLS/apksigner" verify --verbose "$APK"

      - name: Show APK package information
        run: |
          APK="app/build/outputs/apk/debug/app-debug.apk"

          BUILD_TOOLS=$(find "$ANDROID_HOME/build-tools" -maxdepth 1 -type d | sort -V | tail -n 1)

          "$BUILD_TOOLS/aapt" dump badging "$APK"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SSS-Mathematics-APK
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
